dist: trusty
sudo: required
language: node_js

node_js:
  - "node"
  - "7"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser

install:
  - npm install

before_script:
  - npm install -g gulp-cli
script: gulp

cache:
  directories:
    - "node_modules"

deploy:
  provider: azure_web_apps
  file: witweb.zip
  skip_cleanup: true